name: 小米3G
on:
  workflow_dispatch:
jobs:
  build_openwrt:
    name: OpenWrt固件编译
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Space cleanup
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 zip unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 自定义配置
        run: |
          #修改登录IP
          sed -i 's/192.168.1.1/192.168.31.1/g' package/base-files/files/bin/config_generate
      - name: 生成配置文件
        run: |
          rm -f ./.config*
          touch ./.config
          # 固件平台信息
          cat >> .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-3g=y
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true
      - name: 获取当前日期
        run: |
          echo "tag_title=v1.$(TZ=Asia/Shanghai date +'%-m.%-d-%H%M%S')" >> $GITHUB_ENV
          echo "release_pre=v1.$(TZ=Asia/Shanghai date +'%-m.%-d')" >> $GITHUB_ENV
      - name: 整理固件
        run: |
          mkdir -p ./OpenWrt_firmware
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./OpenWrt_firmware
      - name: 上传固件到release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.RELEASE_FIRMWARE }}
          file: OpenWrt_firmware/* 
          tag: ${{ env.tag_title }}
          release_name: "${{ env.release_pre }} 小米3G OpenWrt固件" 
          overwrite: true
          prerelease: false
          body: "登陆IP 192.168.31.1<br/>密码 password"
          file_glob: true
